# Main settings
baseurl: ''
url: https://blog.fractalsoft.org

# Theme
remote_theme: mmistakes/minimal-mistakes
# theme: minimal-mistakes-jekyll

# Meta head
description: Fractal Soft blogs about Ruby on Rails, Ember.js, Backbone.js, React.js and maybe Elixir. Technical blog will be full of web development and the developer community.
locale: pl
title: Web Development in Ruby on Rails, technical blog Fractal Soft
name: Web Development in Ruby on Rails and JavaScript

# Jekyll settings
exclude: ['.keep', '.ruby-gemset', '.ruby-version', '.sass-cache', '_data', '_drafts', '_templates', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
highlighter: rouge
include: ['_data', '_pages']
og_image: /assets/images/fractalsoft/blog.svg
permalink: /:categories/:year/:month/:title/
# permalink: pretty

# Plugins settings
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-pwa-workbox
  - jekyll-redirect-from
  - jekyll-sitemap

# Theme settings
breadcrumbs: false
logo: /assets/images/fractalsoft/blog-44x44.png
masthead_title: Technical blog by Fractal Soft
minimal_mistakes_skin: contrast
og_image: /assets/images/fractalsoft/blog-144x144.png
paginate: 15
paginate_path: /page:num/
search: true
teaser: /assets/images/fractalsoft/blog-222x120.svg
words_per_minute: 150

analytics:
  provider: 'google-gtag'
  google:
    anonymize_ip: false
    tracking_id: 'UA-127776922-2'

category_archive:
  type: liquid
  path: /categories/

collections:
  coderdojo:
    output: true
    permalink: /pl/:collection/:path/

comments:
  provider: 'disqus'
  disqus:
    shortname: 'fractalsoft'

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  # _coderdojo
  - scope:
      path: ''
      type: coderdojo
    values:
      comments: true
      layout: single
      related: true
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      author_profile: true
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      author_profile: true
      comments: true
      read_time: false
      related: true
      share: true

footer:
  links:
    - label: Twitter
      icon: 'fab fa-fw fa-twitter'
      url: https://twitter.com/fractal_soft
    - label: LinkedIn
      icon: 'fab fa-fw fa-linkedin'
      url: https://www.linkedin.com/company/fractalsoft
    - label: YouTube
      icon: 'fab fa-fw fa-youtube'
      url: https://www.youtube.com/c/fractalsoft
    - label: Facebook
      icon: 'fab fa-fw fa-facebook'
      url: https://www.facebook.com/fractalsoft
    - label: Instagram
      icon: 'fab fa-fw fa-instagram'
      url: https://instagram.com/fractalsoft

head_scripts:
  - /assets/js/pwa-1.0.min.js

pwa:
  dest_js_directory: assets/js

sass:
  style: compressed # nested, expended, compact, compressed

tag_archive:
  type: liquid
  path: /tags/

twitter:
  username: fractal_soft

chrome-tab-theme-color: '#1c26c3'
